const products = [
    {
        id: 1,
        title: "Organic Apples",
        description: "Fresh organic apples, perfect for snacking.",
        price: 299,
        discount: 10,
        rating: 4.5,
        thumbnail: "https://b2bgrocery.in/wp-content/uploads/2020/06/organicc-apples-1.png",
        },
        {
        id: 2,
        title: "Whole Wheat Bread",
        description: "Healthy whole wheat bread for your sandwiches.",
        price: 45,
        discount: 5,
        rating: 4.7,
        thumbnail: "https://www.allrecipes.com/thmb/_piMRxT9zYHP39Lnz6-lObHzEWw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-6773-simple-whole-wheat-bread-DDMFS-4x3-B-969e7bce922948959cb9e85aa4b2ff0d.jpg",
        },
        {
        id: 3,
        title: "Fresh Tomatoes",
        description: "Juicy and ripe tomatoes for salads and cooking.",
        price: 70,
        discount: 12,
        rating: 4.6,
        thumbnail: "https://dukaan.b-cdn.net/700x700/webp/upload_file_service/2c3c6711-40f0-4991-bb52-bef290831f16/tomatoes.jpg",
        },
        {
        id: 4,
        title: "Bananas",
        description: "Sweet and ripe bananas packed with energy.",
        price: 50,
        discount: 8,
        rating: 4.5,
        thumbnail: "https://cdn11.bigcommerce.com/s-kc25pb94dz/images/stencil/1280x1280/products/188/602/1-Bunch-Bananas__30199.1650549450.jpg?c=2",
        },
        {
        id: 5,
        title: "Cucumber",
        description: "Fresh cucumbers for salads and snacks.",
        price: 30,
        discount: 10,
        rating: 4.4,
        thumbnail: "https://m.media-amazon.com/images/I/71xkI-PIE5L.jpg",
        },
        {
        id: 6,
        title: "Almonds",
        description: "Crunchy and nutritious almonds, perfect for snacks.",
        price: 200,
        discount: 15,
        rating: 4.8,
        thumbnail: "https://www.healthysupplies.co.uk/cached/1728923172/pics/800x800/organic-almonds-glass-bowl.webp",
        },
        {
        id: 7,
        title: "Milk",
        description: "Fresh and creamy milk for all your dairy needs.",
        price: 60,
        discount: 5,
        rating: 4.7,
        thumbnail: "https://sapinsdairy.com/wp-content/uploads/2021/12/milk-bottle.png",
        },
        {
        id: 8,
        title: "Eggs",
        description: "Farm-fresh eggs for breakfast or baking.",
        price: 50,
        discount: 0,
        rating: 4.6,
        thumbnail: "https://www.fastandup.in/nutrition-world/wp-content/uploads/2023/03/front-view-white-chicken-eggs-inside-basket-with-towel-dark-surface_140725-103357-min.jpg",
        },
        {
        id: 9,
        title: "Fresh Carrots",
        description: "Crunchy and healthy carrots for cooking or snacking.",
        price: 40,
        discount: 8,
        rating: 4.4,
        thumbnail: "https://bcfresh.ca/wp-content/uploads/2021/11/Carrots.jpg",
        },
        {
        id: 10,
        title: "Spinach",
        description: "Fresh spinach for salads or cooking.",
        price: 60,
        discount: 10,
        rating: 4.6,
        thumbnail: "https://www.bluelettuce.in/wp-content/uploads/2022/11/7a16aed2-193e-4e88-bedf-4535b464a285.jpg",
        },
        // Add more grocery items here...
        {
        id: 11,
        title: "Potatoes",
        description: "Fresh and versatile potatoes for all dishes.",
        price: 40,
        discount: 12,
        rating: 4.5,
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu3hixOCV2Ev7g5oonOdjEdC3h_YsNUuEAWaRrGOHOPtrqjRcCwiJEiY0sV26kfVaKblE&usqp=CAU",
        },
        {
        id: 12,
        title: "Rice",
        description: "High-quality basmati rice for a variety of dishes.",
        price: 150,
        discount: 5,
        rating: 4.8,
        thumbnail: "https://bsmedia.business-standard.com/_media/bs/img/article/2024-09/04/full/1725434023-926.jpg",
        },
        {
        id: 13,
        title: "Tomato Sauce",
        description: "Rich and flavorful tomato sauce for pastas and more.",
        price: 120,
        discount: 10,
        rating: 4.6,
        thumbnail: "https://5.imimg.com/data5/SELLER/Default/2023/5/308435640/WL/HD/YV/46063010/20a2d57685d911eda6d5a99be7adc708-variant-5bc87ae20d298a283c29797b-1.jpeg",
        },
        {
        id: 14,
        title: "Olive Oil",
        description: "Pure olive oil for cooking and dressings.",
        price: 250,
        discount: 8,
        rating: 4.7,
        thumbnail: "https://www.soulflower.in/cdn/shop/files/Cold_Pressed_Olive_Oil_for_Nourished_Hair_and_Skin.webp?v=1735196519&width=600",
        },
        {
        id: 15,
        title: "Honey",
        description: "Pure honey for a natural sweetness.",
        price: 180,
        discount: 12,
        rating: 4.8,
        thumbnail: "https://ik.imagekit.io/dunzo/918b0d66cf0c11edb9993a8605d6a439_VARIANT_642168f9ba7a45002670f64d_1.JPG",
        },
        {
        id: 16,
        title: "Lemon",
        description: "Fresh lemons, perfect for juices or seasoning.",
        price: 30,
        discount: 10,
        rating: 4.5,
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXYtXnrGpzC51dtrKar6MZSflJI4ZEJatK1g&s",
        },
        {
        id: 17,
        title: "Green Tea",
        description: "Healthy green tea for your daily boost.",
        price: 120,
        discount: 5,
        rating: 4.7,
        thumbnail: "https://images.ctfassets.net/e8bhhtr91vp3/41XIoxnMHrbQv2AMkqZaO0/edb70fa617e36b27772dfeaee86b124d/Medium-794522730667.01.webp?w=800&q=50",
        },
        {
        id: 18,
        title: "Yogurt",
        description: "Fresh yogurt, perfect for breakfast or smoothies.",
        price: 80,
        discount: 8,
        rating: 4.6,
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1jDsBo3p85KYU0ZESV1WRqeJI1zCrNoc1GQ&s",
        },
        {
        id: 19,
        title: "Frozen Peas",
        description: "Frozen peas for quick cooking.",
        price: 90,
        discount: 5,
        rating: 4.4,
        thumbnail: "https://www.smc-madhusudan.co.in/cdn/shop/files/MadhusudanFrozenGreenPea500gFrontDummy_1.png?v=1714552196&width=1412",
        },
        {
        id: 20,
        title: "Coconut Oil",
        description: "Pure coconut oil for cooking or skincare.",
        price: 250,
        discount: 15,
        rating: 4.6,
        thumbnail: "https://m.media-amazon.com/images/I/71+I2IPZOqL._AC_UF1000,1000_QL80_.jpg",
        },
        {
        id: 21,
        title: "Cereal",
        description: "Healthy and nutritious breakfast cereal.",
        price: 150,
        discount: 10,
        rating: 4.7,
        thumbnail: "https://www.kelloggs.com/content/dam/Asia/kelloggs_in/images/articles/benefits-of-cereal.jpg",
        },
        {
        id: 22,
        title: "Chickpeas",
        description: "Dried chickpeas for cooking and snacking.",
        price: 100,
        discount: 8,
        rating: 4.5,
        thumbnail: "https://nutritionsource.hsph.harvard.edu/wp-content/uploads/2024/11/AdobeStock_118383793.jpeg",
        },
        {
        id: 23,
        title: "Pasta",
        description: "High-quality pasta for your favorite dishes.",
        price: 80,
        discount: 5,
        rating: 4.6,
        thumbnail: "https://gharstuff.com/wp-content/uploads/2020/04/Maggi-Masala-Penne-Instant-Pasta-65g-1.jpg",
        },
        {
        id: 24,
        title: "Chocolate",
        description: "Delicious chocolate for your sweet cravings.",
        price: 150,
        discount: 12,
        rating: 4.7,
        thumbnail: "https://www.quickpantry.in/cdn/shop/products/cadbury-dairy-milk-silk-chocolate-bar-60-g-quick-pantry.jpg?v=1710538483&width=500",
        },
        {
        id: 25,
        title: "Salt",
        description: "Pure salt for cooking and seasoning.",
        price: 20,
        discount: 0,
        rating: 4.4,
        thumbnail: "https://jindalnaturecure.in/wp-content/uploads/2018/11/Beware-of-common-salt.jpg",
        },
        {
            id: 1,
            title: "Apple iPhone 14",
            description: "The latest iPhone with advanced features and stunning design.",
            price: 79999,
            discount: 10,
            rating: 4.8,
            thumbnail: "https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_UF1000,1000_QL80_.jpg",
            About: [
              "Bank Offer: 5% Unlimited Cashback on Flipkart Axis Bank Credit Card. T&C apply.",
              "Bank Offer: 10% off up to ₹500 on HDFC Bank Credit Card EMI transactions on 3-month tenure. Min. Transaction Value: ₹5000. T&C apply.",
              "Bank Offer: 10% off up to ₹1,000 on HDFC Bank Credit Card EMI for 6 and 9-month tenures. Min. Transaction Value: ₹5000. T&C apply.",
              "Extra Offer: 10% off on Combo with Mobile - Apple. T&C apply."
            ]
          },

        {
          id: 2,
          title: "Samsung Galaxy S23",
          description: "Experience cutting-edge technology with the Galaxy S23.",
          price: 74999,
          discount: 15,
          rating: 4.6,
          thumbnail: "https://media.croma.com/image/upload/v1675347470/Croma%20Assets/Communication/Mobiles/Images/268868_u7nsk3.png",
          About: [
            "Bank Offer: 5% Unlimited Cashback on Flipkart Axis Bank Credit Card. T&C apply.",
            "Bank Offer: 10% off up to ₹500 on HDFC Bank Credit Card EMI transactions on 3-month tenure. Min. Transaction Value: ₹5000. T&C apply.",
            "Bank Offer: 10% off up to ₹1,000 on HDFC Bank Credit Card EMI for 6 and 9-month tenures. Min. Transaction Value: ₹5000. T&C apply.",
            "Extra Offer: 10% off on Combo with Mobile - Apple. T&C apply."
          ]
        },
        {
          id: 3,
          title: "Sony WH-1000XM5",
          description: "Premium noise-cancelling headphones for an immersive sound experience.",
          price: 29999,
          discount: 20,
          rating: 4.7,
          thumbnail: "https://www.sony.co.in/image/f4b4580f439b31bd31ad70c393983cd1?fmt=png-alpha&wid=1014&hei=396",
        },
        {
          id: 4,
          title: "Sony TV",
          description: "Sony 139 cm (55 inches) BRAVIA 2 4K Ultra HD Smart LED Google TV K-55S25B (Black)",
          price: 57999,
          discount: 20,
          rating: 4.0,
          thumbnail: "https://m.media-amazon.com/images/I/81zPuf-0ETL._SL1500_.jpg",
        },
        {
          id: 5,
          title: "Adidas Shoes",
          description: "Adidas Mens Glowrun Reflective M Running Shoe",
          price: 1800,
          discount: 20,
          rating: 3.9,
          thumbnail: "https://m.media-amazon.com/images/I/81llmseSUJL._SX695_.jpg",
          About: [
            "Bank Offer: 5% Unlimited Cashback on Flipkart Axis Bank Credit Card. T&C apply.",
            "Bank Offer: 10% off up to ₹500 on HDFC Bank Credit Card EMI transactions on 3-month tenure. Min. Transaction Value: ₹5000. T&C apply.",
            "Bank Offer: 10% off up to ₹1,000 on HDFC Bank Credit Card EMI for 6 and 9-month tenures. Min. Transaction Value: ₹5000. T&C apply.",
            "Extra Offer: 10% off on Combo with Mobile - Apple. T&C apply."
          ]
        },
        {
          id: 6,
          title: "Aerokick Kids Sneakers",
          description: "Aerokick Kids Casual Sneaker Shoes, Lightweight, Durable, Comfortable Casual Shoes for Boys and Girls",
          price: 473,
          discount: 57,
          rating: 3.1,
          thumbnail: "https://m.media-amazon.com/images/I/51CMd6Lv+kL._SY695_.jpg",
        },
        {
          id: 7,
          title: "Generic",
          description: "MADEEHA Chikankari Lucknow Handwork MUL MUL Printed Kurti",
          price: 1600,
          discount: 7,
          rating: 3.1,
          thumbnail: "https://m.media-amazon.com/images/I/612qREowxPL._SY741_.jpg",
        },
        {
          id: 8,
          title: "Generic",
          description: "PK HUB Rajasthani Womens Chiffon Fabric Leheriya Saree Traditional Ethnic Sari Jaipuri Fashion Dress",
          price: 1000,
          discount: 77,
          rating: 4.1,
          thumbnail: "https://m.media-amazon.com/images/I/71mnVIfdp8L._SY741_.jpg",
        },
        {
          id: 9,
          title: "Tommy Hilfiger",
          description: "Tommy Hilfiger Multifunction Black Dial Watch for Men",
          price: 9999,
          discount: 77,
          rating: 4.3,
          thumbnail: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw42068a45/images/Helios/Catalog/TH1791986_1.jpg?sw=600&sh=600",
        },

        {
            id: 10  ,
            title: "Titan",
            description: "Titan Unity Automatic Leather Strap Watch For Men - Limited Series - Stellar Edition",
            price:3999,
            discount: 27,
            rating: 4.3,
            thumbnail: "https://www.titan.co.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw2aa44747/images/Titan/Catalog/1796SL01_2.jpg?sw=600&sh=600",
          },
          {
            id: 11  ,
            title: "AASHIRVAAD",
            description: "AASHIRVAAD Shudh Chakki Atta (Akha Ghauno Lot)  (10 kg)",
            price:525,
            discount: 13,
            rating: 4,
            thumbnail: "https://rukminim2.flixcart.com/image/280/280/xif0q/flour/j/n/v/-original-imagm7w8jfn29hp2.jpeg?q=70",
          },

          {
            id: 12 ,
            title: "Thums Up",
            description: "Thums Up Soft Drink (750 ml)",
            price:25,
            discount: 3,
            rating: 4.7,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/assets/products/sliding_images/jpeg/e69c587d-802a-40eb-a40b-a6bc9623526d.jpg?ts=1707312325",
          },
          {
            id: 13 ,
            title: "Durex",
            description: "Durex Air Ultra Thin Condom - 3 units",
            price:110,
            discount: 7,
            rating: 2.9,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/assets/products/sliding_images/jpeg/077e830c-640b-4b54-a9cb-149c7870de42.jpg?ts=1726465586",
          },
          {
            id: 14 ,
            title: "Moov",
            description: "Moov Instant Pain Relief Spray",
            price:370,
            discount: 17,
            rating: 3.9,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/18862a.jpg?ts=1687262752",
          },

          {
            id: 15 ,
            title: "Amul Gee",
            description: "Amul Cow Ghee (Tin)",
            price:665,
            discount: 7,
            rating: 3.9,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/197187a.jpg?ts=1698063518",
          },

          {
            id: 16 ,
            title: "PIXI ",
            description: "PIXI Glow Tonic Exfoliating Toner With Glycolic Acid(100ml)",
            price:1555,
            discount: 27,
            rating: 3,
            thumbnail: "https://images-static.nykaa.com/media/catalog/product/tr:w-220,h-220,cm-pad_resize/a/5/a5fe676885190821020b_b1.jpg",
          },

          {
            id: 17 ,
            title: "Lakmē ",
            description: "Lakmē 9 to 5 CC Cream ",
            price:300,
            discount: 5,
            rating: 3.4,
            thumbnail: "https://www.lakmeindia.com/cdn/shop/products/Lakme9to5CCComplexionCareCream_30gmHoney_1000x.jpg?v=1598102848",
          },
          {
            id: 18 ,
            title: "Lakmē ",
            description: "Lakmē Facelift MultiSlayer Blush Stick  ",
            price:900,
            discount: 15,
            rating: 3.2,
            thumbnail: "https://www.lakmeindia.com/cdn/shop/files/1000x1000facestickSupplementryNEW_FOP-coralqueen_1000x.jpg?v=1735018916",
          },

          {
            id: 19 ,
            title: "Lakmē ",
            description: "Lakmē 9to5 Powerplay Priming Foundation  ",
            price:650,
            discount: 14,
            rating: 3.6,
            thumbnail: "https://www.lakmeindia.com/cdn/shop/files/24451_H-8901030742436_1000x.jpg?v=1712053120",
          },
          {
            id: 20 ,
            title: "Fastrack ",
            description: "White Quilted Tote Bag  ",
            price:2959,
            discount: 10,
            rating: 3,
            thumbnail: "https://www.fastrack.in/dw/image/v2/BKDD_PRD/on/demandware.static/-/Sites-titan-master-catalog/default/dw272270fc/images/Fastrack/Catalog/F241TOMEN03WH1_1.jpg?sw=600&sh=600",
          },
          {
            id: 21 ,
            title: "Regular Fit Hoodie ",
            description: "Long-sleeved hoodie in midweight sweatshirt fabric with a soft brushed inside. Kangaroo pocket, double-layered drawstring hood with a wrapover front, and ribbing at the cuffs and hem. Regular fit for comfortable wear and a classic silhouette.  ",
            price:2999,
            discount: 50,
            rating: 3.8,
            thumbnail: "https://lp2.hm.com/hmgoepprod?set=source[/bc/32/bc3215924e85421396ec36e835bd00cbce55a9d7.jpg],origin[dam],category[men_hoodiessweatshirts_hoodies],type[DESCRIPTIVESTILLLIFE],res[s],hmver[2]&call=url[file:/product/main]",
          },

          {
            id: 22 ,
            title: "Regular Fit Hoodie ",
            description: "Jacket in a soft weave featuring notch lapels with a decorative buttonhole and a two-button fastening at the front. Jetted front pockets with a flap, a chest pocket, two inner pockets, decorative buttons at the cuffs and a single back vent. Relaxed fit for a casual but not oversized silhouette. Lined. ",
            price:6999,
            discount: 11,
            rating: 4.1,
            thumbnail: "https://lp2.hm.com/hmgoepprod?set=quality%5B79%5D%2Csource%5B%2Fe9%2F0c%2Fe90cd7b743cd5ce27b97c5033583765a972a78f6.jpg%5D%2Corigin%5Bdam%5D%2Ccategory%5B%5D%2Ctype%5BDESCRIPTIVESTILLLIFE%5D%2Cres%5Bm%5D%2Chmver%5B2%5D&call=url[file:/product/fullscreen]",
          },
          {
            id: 23 ,
            title: "Tomato ",
            description: "Desi Tomato",
            price:33,
            discount: 4,
            rating: 4,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/assets/products/sliding_images/jpeg/442798c8-4004-41a6-94b5-3ffba5b9f0c1.jpg?ts=1717305398",
          },

          {
            id: 24 ,
            title: "Brinjal ",
            description: "Round Purple Brinjal",
            price:35,
            discount: 25,
            rating: 2.8,
            thumbnail: "https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=270/app/images/products/sliding_image/540504a.jpg",
          },
          {
            id: 25 ,
            title: "Tawas ",
            description: "Kreme Cookwell series Nonstick Granite Non-Induction Flat Dosa Tawa 28 cm diameter  (Aluminium, Non-stick)",
            price:1999,
            discount: 65,
            rating: 4.2,
            thumbnail: "https://rukminim2.flixcart.com/image/612/612/xif0q/pot-pan/8/5/c/kan072-kreme-original-imagtrfhryaemght.jpeg?q=70",
          },

          {
            id: 26 ,
            title: "LG ",
            description: "LG AI Convertible 6-in-1 Cooling 2024 Model 1 Ton 5 Star Split Inverter 4 Way Air Swing HD Filter with Anti-Virus Protection AC with VIRAAT Mode & ADC Sensor AC - White  (TS-Q14YNZE, Copper Condenser)",
            price:75000,
            discount: 35,
            rating: 3.8,
            thumbnail: "https://rukminim2.flixcart.com/image/312/312/xif0q/air-conditioner-new/z/v/n/-original-imah3g7sgjsv2a4g.jpeg?q=70",
          },
          {
            id: 27 ,
            title: " SONY Playstation",
            description: "SONY Playstation 4 Brand New Ps4 Slim Console 1TB  (Black, With Extra Dusalshock 4 Red Controller, Yes)",
            price:45000,
            discount: 35,
            rating: 3.2,
            thumbnail: "https://rukminim2.flixcart.com/image/612/612/xif0q/gamingconsole/i/z/i/1tb-playstation-4-brand-new-ps4-slim-console-sony-yes-original-imah4d64pjay2r8w.jpeg?q=70",
          },
          {
            id: 1,
            title: "Maybelline Fit Me Foundation",
            description: "Liquid foundation for a natural matte finish.",
            price: 549,
            discount: 20,
            rating: 4.5,
            thumbnail: "https://m.media-amazon.com/images/I/71hZifnguxL.jpg",
            },
            {
            id: 2,
            title: "Lakmé Absolute Lipstick",
            description: "Rich color, long-lasting lipstick for every occasion.",
            price: 800,
            discount: 15,
            rating: 4.3,
            thumbnail: "https://m.media-amazon.com/images/I/41FBoQstt8L._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 3,
            title: "L'Oréal Paris Kajal",
            description: "Waterproof, smudge-proof kajal for bold eyes.",
            price: 299,
            discount: 10,
            rating: 4.6,
            thumbnail: "https://m.media-amazon.com/images/I/41v9meBW1xL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 4,
            title: "MAC Studio Fix Powder",
            description: "2-in-1 foundation and powder for a flawless finish.",
            price: 2900,
            discount: 25,
            rating: 4.8,
            thumbnail: "https://m.media-amazon.com/images/I/410xc0bn4UL.jpg",
            },
            {
            id: 5,
            title: "Neutrogena Hydro Boost Gel",
            description: "Hydrating gel for soft, supple skin.",
            price: 950,
            discount: 10,
            rating: 4.4,
            thumbnail: "https://m.media-amazon.com/images/I/31wlq1RSIRL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 6,
            title: "The Body Shop Tea Tree Oil",
            description: "Targeted solution for blemished skin.",
            price: 695,
            discount: 5,
            rating: 4.2,
            thumbnail: "https://m.media-amazon.com/images/I/31LLePfgxhL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 7,
            title: "Nivea Soft Cream",
            description: "Light moisturizing cream for daily use.",
            price: 299,
            discount: 10,
            rating: 4.1,
            thumbnail: "https://m.media-amazon.com/images/I/313JkNmP1-L._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 8,
            title: "Himalaya Purifying Neem Face Wash",
            description: "Cleansing face wash with neem and turmeric.",
            price: 165,
            discount: 20,
            rating: 4.7,
            thumbnail: "https://m.media-amazon.com/images/I/41oFB2tM5BL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
            id: 9,
            title: "Plum Green Tea Toner",
            description: "Alcohol-free toner for oily skin.",
            price: 390,
            discount: 15,
            rating: 4.3,
            thumbnail: "https://m.media-amazon.com/images/I/41e5GXEhpeL._SX522_.jpg",
            },
            {
            id: 10,
            title: "Biotique Bio Dandelion Serum",
            description: "Brightening serum for all skin types.",
            price: 230,
            discount: 18,
            rating: 4.2,
            thumbnail: "https://m.media-amazon.com/images/I/51BPHahtYxL.jpg ",
            },

            {
                id: 11,
                title: "Maybelline SuperStay Matte Ink",
                description: "Long-lasting liquid lipstick with intense color.",
                price: 650,
                discount: 15,
                rating: 4.6,
                thumbnail: "https://m.media-amazon.com/images/I/315NWHtfujL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
                id: 12,
                title: "Lakmé Sun Expert Sunscreen",
                description: "SPF 50 PA+++ sunscreen for sun protection.",
                price: 499,
                discount: 10,
                rating: 4.3,
                thumbnail: "https://m.media-amazon.com/images/I/313AkV5je6L._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
                id: 13,
                title: "L'Oréal Paris Hair Serum",
                description: "Smoothing serum for frizz-free, shiny hair.",
                price: 550,
                discount: 12,
                rating: 4.5,
                thumbnail: "https://m.media-amazon.com/images/I/61GGg1vs3DL._SX679_.jpg",
            },
            {
                id: 14,
                title: "MAC Retro Matte Lipstick",
                description: "High pigment matte lipstick for bold lips.",
                price: 1700,
                discount: 20,
                rating: 4.8,
                thumbnail: "https://beautifulstore.in/wp-content/uploads/2024/04/41HuFvu4QL._SX679_.jpg",
            },
            {
                id: 15,
                title: "Neutrogena Ultra Sheer Dry-Touch Sunscreen",
                description: "Lightweight SPF 50+ sunscreen for broad-spectrum protection.",
                price: 650,
                discount: 15,
                rating: 4.4,
                thumbnail: "https://images-cdn.ubuy.co.id/661bfb4b339fb87b5724cd53-neutrogena-ultra-sheer-dry-touch-spf-100.jpg",
            },
            {
                id: 16,
                title: "The Body Shop Vitamin E Cream",
                description: "Moisturizing cream with Vitamin E for all-day hydration.",
                price: 995,
                discount: 10,
                rating: 4.6,
                thumbnail: "https://www.bigbasket.com/media/uploads/p/xl/40112730_3-the-body-shop-moisture-cream-vitamin-e.jpg",
            },
            {
                id: 17,
                title: "Nivea Men Dark Spot Reduction Cream",
                description: "Face cream for men with UV protection.",
                price: 280,
                discount: 8,
                rating: 4.1,
                thumbnail: "https://m.media-amazon.com/images/I/51NYSJRXJ6L._AC_UL320_.jpg",
            },
            {
                id: 18,
                title: "Himalaya Herbals Nourishing Skin Cream",
                description: "Daily moisturizing cream with herbal extracts.",
                price: 140,
                discount: 15,
                rating: 4.2,
                thumbnail: "https://m.media-amazon.com/images/I/61N2NtfMc9L._AC_UL320_.jpg",
            },
            {
                id: 19,
                title: "Plum Grape Seed & Sea Buckthorn Oil",
                description: "Natural facial oil for glowing skin.",
                price: 550,
                discount: 18,
                rating: 4.3,
                thumbnail: "https://m.media-amazon.com/images/I/31MwIWcVwOL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
                id: 20,
                title: "Biotique Morning Nectar Lotion",
                description: "Hydrating lotion for a glowing complexion.",
                price: 180,
                discount: 12,
                rating: 4.0,
                thumbnail: "https://m.media-amazon.com/images/I/71wUhQVqYmL._AC_UL320_.jpg",
            },
            {
                id: 21,
                title: "Maybelline Colossal Mascara",
                description: "Volumizing waterproof mascara for dramatic lashes.",
                price: 399,
                discount: 10,
                rating: 4.4,
                thumbnail: "https://m.media-amazon.com/images/I/51PQhsaEcLL._AC_UL320_.jpg",
            },
            {
                id: 22,
                title: "Lakmé Rose Face Powder",
                description: "Loose face powder with sunscreen for matte finish.",
                price: 170,
                discount: 20,
                rating: 4.2,
                thumbnail: "https://m.media-amazon.com/images/I/412TSWSvo6L.jpg",
            },
            {
                id: 23,
                title: "L'Oréal Paris Revitalift Night Cream",
                description: "Anti-aging night cream for youthful skin.",
                price: 999,
                discount: 15,
                rating: 4.5,
                thumbnail: "https://m.media-amazon.com/images/I/31m-4+Bv8CL._SY300_SX300_DpWeblab_.jpg",
            },
            {
                id: 24,
                title: "MAC Pro Longwear Concealer",
                description: "Lightweight concealer for full coverage.",
                price: 2200,
                discount: 25,
                rating: 4.7,
                thumbnail: "https://m.media-amazon.com/images/I/61OxOxR9aoL._AC_UL320_.jpg",
            },
            {
                id: 25,
                title: "Neutrogena Deep Clean Facial Cleanser",
                description: "Gentle cleanser for removing dirt and oil.",
                price: 425,
                discount: 10,
                rating: 4.3,
                thumbnail: "https://m.media-amazon.com/images/I/31qUekdzfyL._SX300_SY300_QL70_FMwebp_.jpg",
            },
            {
                id: 1,
                title: "Apple iPhone 14",
                description: "128GB, Midnight - 5G smartphone.",
                price: 79999,
                discount: 10,
                rating: 4.8,
                thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVRZPh1_spmFWCrUzs58SqLNpLNtLcz0UnBw&s",
              },
              {
                id: 2,
                title: "Dell Inspiron 15 Laptop",
                description: "11th Gen Intel Core i5, 16GB RAM, 512GB SSD.",
                price: 58999,
                discount: 15,
                rating: 4.5,
                thumbnail: "https://m.media-amazon.com/images/I/91XDOjF1TzL._AC_UF894,1000_QL80_.jpg",
              },
              {
                id: 3,
                title: "Sony Bravia 43-inch TV",
                description: "4K Ultra HD Smart LED TV.",
                price: 45999,
                discount: 12,
                rating: 4.7,
                thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPCiy6mLQYIFXH5xxJ8_msS9nqtWfYAE2ILw&s",
              },
              {
                id: 4,
                title: "Bose QuietComfort Earbuds",
                description: "Noise-canceling true wireless earbuds.",
                price: 22999,
                discount: 8,
                rating: 4.6,
                thumbnail: "https://m.media-amazon.com/images/I/61CGHv6kmWL._SL1500_.jpg",
              },
              {
                id: 5,
                title: "Logitech MX Master 3 Mouse",
                description: "Advanced wireless mouse with ergonomic design.",
                price: 7499,
                discount: 10,
                rating: 4.8,
                thumbnail: "https://m.media-amazon.com/images/I/61ni3t1ryQL._AC_UF1000,1000_QL80_.jpg",
              },
              {
                id: 6,
                title: "Sony WH-1000XM5 Headphones",
                description: "Wireless noise-canceling headphones.",
                price: 29999,
                discount: 12,
                rating: 4.9,
                thumbnail: "https://buy.budli.in/cdn/shop/files/Untitleddesign-2024-12-07T121227.322.jpg?v=1733553813&width=1946",
              },
              {
                id: 7,
                title: "JBL Flip 6 Bluetooth Speaker",
                description: "Portable waterproof speaker with deep bass.",
                price: 9999,
                discount: 20,
                rating: 4.5,
                thumbnail: "https://in.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw4c84a098/2_JBL_FLIP6_3_4_RIGHT_BLACK_30195_x1.png?sw=535&sh=535",
              },
              {
                id: 8,
                title: "Samsung Split AC 1.5 Ton",
                description: "5-star inverter air conditioner with Wi-Fi.",
                price: 40999,
                discount: 18,
                rating: 4.4,
                thumbnail: "https://m.media-amazon.com/images/I/61xQNSWHzqL.jpg",
              },
              {
                  id: 9,
                  title: "Asus ROG Strix Gaming Laptop",
                  description: "AMD Ryzen 7, 16GB RAM, 1TB SSD, RTX 3060.",
                  price: 124999,
                  discount: 10,
                  rating: 4.7,
                  thumbnail: "https://www.excaliberpc.com/images/798022_4/original.jpg",
                },
                {
                  id: 10,
                  title: "Amazon Echo Dot (5th Gen)",
                  description: "Smart speaker with Alexa - Charcoal.",
                  price: 4499,
                  discount: 15,
                  rating: 4.6,
                  thumbnail: "https://www.jiomart.com/images/product/original/493711732/amazon-echo-dot-5th-gen-smart-speaker-2023-blue-digital-o493711732-p598989290-0-202312042006.jpeg?im=Resize=(1000,1000)",
                },
                {
                  id: 11,
                  title: "GoPro HERO11 Black",
                  description: "Waterproof action camera with 5.3K video.",
                  price: 44999,
                  discount: 12,
                  rating: 4.8,
                  thumbnail: "https://retinapix.com/cdn/shop/files/GoProHero11BlackActionCamera_2_1200x1200.jpg?v=1723308292",
                },
                {
                  id: 12,
                  title: "Apple Watch Series 9",
                  description: "45mm GPS smartwatch with Always-On display.",
                  price: 41999,
                  discount: 10,
                  rating: 4.9,
                  thumbnail: "https://www.maplestore.in/cdn/shop/files/Apple_Watch_Series_9_GPS_45mm_Pink_Aluminium_Light_Pink_Sport_Band_PDP_Image_Position-1__en-IN_743f7781-987b-4248-9f3a-f1ad9f832388.jpg?v=1701896659&width=1445",
                },
                {
                  id: 13,
                  title: "Samsung Galaxy Tab S9",
                  description: "12.4-inch AMOLED tablet with S Pen.",
                  price: 79999,
                  discount: 15,
                  rating: 4.7,
                  thumbnail: "https://images.samsung.com/is/image/samsung/p6pim/in/sm-x710nzaainu/gallery/in-galaxy-tab-s9-wifi-x710-sm-x710nzaainu-thumb-537885436",
                },
                {
                  id: 14,
                  title: "Anker PowerCore 20,000mAh",
                  description: "Portable power bank with fast charging.",
                  price: 2499,
                  discount: 20,
                  rating: 4.6,
                  thumbnail: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6405/6405177_sd.jpg",
                },
                {
                  id: 15,
                  title: "Canon EOS R10 Camera",
                  description: "24.2MP mirrorless camera with 18-150mm lens.",
                  price: 114999,
                  discount: 8,
                  rating: 4.8,
                  thumbnail: "https://rukminim2.flixcart.com/image/850/1000/l5fnhjk0/dslr-camera/f/t/m/eos-r10-24-2-r10-canon-original-imagg42fsbgv79da.jpeg?q=90&crop=false",
                },
                {
                  id: 16,
                  title: "LG 27-inch 4K Monitor",
                  description: "UHD IPS display with HDR10 and USB-C.",
                  price: 37999,
                  discount: 10,
                  rating: 4.7,
                  thumbnail: "https://dnacomputers.in/wp-content/uploads/2022/12/LG-27-inch-4K-UHD-HDR-10-Monitor-removebg-preview.png.webp",
                },
                {
                  id: 17,
                  title: "HyperX Alloy FPS Keyboard",
                  description: "Mechanical gaming keyboard with RGB lighting.",
                  price: 8999,
                  discount: 15,
                  rating: 4.5,
                  thumbnail: "https://images-cdn.ubuy.co.in/66392ce393fd6355963b34f5-hyperx-alloy-fps-rgb-mechanical-gaming.jpg",
                },
                {
                  id: 18,
                  title: "Dyson V15 Detect Vacuum Cleaner",
                  description: "Cordless vacuum with laser dirt detection.",
                  price: 67999,
                  discount: 8,
                  rating: 4.9,
                  thumbnail: "https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1658738205/Croma%20Assets/Small%20Appliances/Vacuum%20Cleaners/Images/257377_elpr55.png   ",
                },
                {
                  id: 19,
                  title: "Microsoft Surface Laptop 5",
                  description: "13.5-inch touchscreen, Intel i7, 16GB RAM.",
                  price: 124999,
                  discount: 10,
                  rating: 4.7,
                  thumbnail: "https://cdn-dynmedia-1.microsoft.com/is/image/microsoftcorp/MSFT-Up-level-the-way-you-work-RE50wv8?fmt=png-alpha&scl=1",
                },
                {
                  id: 20,
                  title: "Beats Studio Buds",
                  description: "True wireless earbuds with active noise canceling.",
                  price: 12999,
                  discount: 12,
                  rating: 4.6,
                  thumbnail: "https://www.aptronixindia.com/media/catalog/product/cache/31f0162e6f7d821d2237f39577122a8a/s/t/studiobudsplus-ivory-01.png",
                },
                {
                  id: 21,
                  title: "Fitbit Charge 5",
                  description: "Advanced fitness tracker with built-in GPS.",
                  price: 12999,
                  discount: 15,
                  rating: 4.5,
                  thumbnail: "https://m.media-amazon.com/images/I/61PmMzYM4qL.jpg",
                },
                {
                  id: 22,
                  title: "NVIDIA Shield TV Pro",
                  description: "4K HDR streaming media player with GeForce NOW.",
                  price: 16999,
                  discount: 10,
                  rating: 4.7,
                  thumbnail: "https://m.media-amazon.com/images/I/51ZGCIbrgFL._AC_UF1000,1000_QL80_.jpg",
                },
                {
                    id: 1,
                    category: "Men",
                    title: "Casual T-shirt",
                    description: "Comfortable and stylish casual t-shirt for everyday wear.",
                    price: 799,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://ae01.alicdn.com/kf/S67257c90b13748e5a293024dc523f382A.jpg",
                  },
                  {
                    id: 2,
                    category: "Men",
                    title: "Designer Jeans",
                    description: "Trendy jeans with a perfect fit.",
                    price: 1999,
                    discount: 15,
                    rating: 4.7,
                    thumbnail: "https://assets.ajio.com/medias/sys_master/root/20210526/K6sB/60ae653ef997ddb312aaebcf/-473Wx593H-410173824-2authenticdrk-MODEL.jpg",
                  },
                  {
                    id: 3,
                    category: "Men",
                    title: "Leather Jacket",
                    description: "Premium leather jacket for a fashionable look.",
                    price: 4999,
                    discount: 20,
                    rating: 4.8,
                    thumbnail: "https://www.voganow.com/cdn/shop/files/BBGJ-1108-014_2_copy.jpg?v=1702101740&width=360",
                  },
                  {
                    id: 4,
                    category: "Men",
                    title: "Sneakers",
                    description: "Stylish sneakers for an active lifestyle.",
                    price: 2499,
                    discount: 10,
                    rating: 4.6,
                    thumbnail: "https://cdn.thewirecutter.com/wp-content/media/2024/05/white-sneaker-2048px-9320.jpg?auto=webp&quality=75&crop=1.91:1&width=1200",
                  },
                  {
                    id: 5,
                    category: "Men",
                    title: "Summer Shorts",
                    description: "Perfect for the summer days, comfortable shorts.",
                    price: 899,
                    discount: 12,
                    rating: 4.4,
                    thumbnail: "https://img.joomcdn.net/28e4dae837d8f159d7db8ec7f14a03c7fe4269fa_original.jpeg",
                  },

                  // Women Products
                  {
                    id: 6,
                    category: "Women",
                    title: "Floral Dress",
                    description: "Elegant floral dress for parties and gatherings.",
                    price: 2299,
                    discount: 20,
                    rating: 4.6,
                    thumbnail: "https://target.scene7.com/is/image/Target/GUEST_b843c3a4-d1ac-478e-985d-f2590972ce59?wid=488&hei=488&fmt=pjpeg",
                  },
                  {
                    id: 7,
                    category: "Women",
                    title: "Silk Scarf",
                    description: "Luxurious silk scarf to elevate your outfit.",
                    price: 1299,
                    discount: 15,
                    rating: 4.7,
                    thumbnail: "https://s.alicdn.com/@sc04/kf/UTB8a8DmJyDEXKJk43Oqq6Az3XXay.jpg_720x720q50.jpg",
                  },
                  {
                    id: 8,
                    category: "Women",
                    title: "Heeled Boots",
                    description: "Chic heeled boots perfect for formal events.",
                    price: 3999,
                    discount: 25,
                    rating: 4.5,
                    thumbnail: "https://m.media-amazon.com/images/I/71+P0R5d8SL._AC_UY1000_.jpg",
                  },
                  {
                    id: 9,
                    category: "Women",
                    title: "Blouse",
                    description: "Lightweight blouse for casual and work settings.",
                    price: 1599,
                    discount: 10,
                    rating: 4.4,
                    thumbnail: "https://aadvi.in/cdn/shop/products/File_040.jpg?v=1612953817",
                  },
                  {
                    id: 10,
                    category: "Women",
                    title: "Denim Skirt",
                    description: "Trendy denim skirt for a casual yet chic look.",
                    price: 1299,
                    discount: 5,
                    rating: 4.3,
                    thumbnail: "https://di2ponv0v5otw.cloudfront.net/posts/2023/06/28/649cc21c02760b97dba290ca/m_wp_649cc231dbb0e73fd6585650.webp",
                  },

                  // Kids Products
                  {
                    id: 11,
                    category: "Kids",
                    title: "Cartoon T-shirt",
                    description: "Fun cartoon-themed t-shirt for kids.",
                    price: 499,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://5.imimg.com/data5/KR/LN/MY-31533998/ladies-cartoon-t-shirt.jpg",
                  },
                  {
                    id: 12,
                    category: "Kids",
                    title: "Cute Hoodie",
                    description: "Comfy hoodie for the little ones, perfect for cold days.",
                    price: 899,
                    discount: 15,
                    rating: 4.6,
                    thumbnail: "https://images.meesho.com/images/products/441276012/ukkva_512.webp",
                  },
                  {
                    id: 13,
                    category: "Kids",
                    title: "Velvet Dress",
                    description: "Soft and stylish velvet dress for girls.",
                    price: 1299,
                    discount: 20,
                    rating: 4.8,
                    thumbnail: "https://m.media-amazon.com/images/I/61tPsB8cm3L._AC_UY1100_.jpg",
                  },
                  {
                    id: 14,
                    category: "Kids",
                    title: "Sneakers for Kids",
                    description: "Comfortable sneakers for kids' outdoor activities.",
                    price: 999,
                    discount: 5,
                    rating: 4.5,
                    thumbnail: "https://images-cdn.ubuy.co.in/66742a61ce26da0a7343cd83-baby-shoes-children-boys-bling-led-light.jpg",
                  },
                  {
                    id: 15,
                    category: "Kids",
                    title: "Teddy Bear Pajamas",
                    description: "Adorable teddy bear-themed pajamas for kids.",
                    price: 799,
                    discount: 10,
                    rating: 4.6,
                    thumbnail: "https://thetrendytoddlers.com/cdn/shop/products/1_32901911-428f-43ae-8d32-a810c46ab26e_1024x1024.jpg?v=1659511492",
                  },

                  // More products for Men, Women, and Kids
                  {
                    id: 16,
                    category: "Men",
                    title: "Sporty Tracksuit",
                    description: "Comfortable tracksuit for the athletic men.",
                    price: 2499,
                    discount: 10,
                    rating: 4.6,
                    thumbnail: "https://shivnaresh.in/cdn/shop/files/1_3_b5800b76-12d1-48d1-95ee-d3470c652d12.jpg?v=1734164059&width=600",
                  },
                  {
                    id: 17,
                    category: "Men",
                    title: "Formal Shirt",
                    description: "Sharp and stylish formal shirt for work.",
                    price: 1499,
                    discount: 15,
                    rating: 4.8,
                    thumbnail: "https://blackberrys.com/cdn/shop/files/printed-formal-shirt-in-blue-jedi-blackberrys-clothing-1_1200x1200.jpg?v=1685949827",
                  },
                  {
                    id: 18,
                    category: "Women",
                    title: "Evening Gown",
                    description: "Elegant evening gown for special occasions.",
                    price: 7999,
                    discount: 30,
                    rating: 4.9,
                    thumbnail: "https://m.media-amazon.com/images/I/61GC5xBjHyL.jpg",
                  },
                  {
                    id: 19,
                    category: "Women",
                    title: "Trench Coat",
                    description: "Stylish trench coat for the autumn season.",
                    price: 3999,
                    discount: 20,
                    rating: 4.6,
                    thumbnail: "https://www.mytheresa.com/media/1094/1238/100/15/P00888002.jpg",
                  },
                  {
                    id: 20,
                    category: "Kids",
                    title: "Raincoat",
                    description: "Colorful raincoat for kids to enjoy the rainy days.",
                    price: 1299,
                    discount: 5,
                    rating: 4.7,
                    thumbnail: "https://images-cdn.ubuy.co.in/65463db7a8f1f178330047a3-yiluweinir-age-3-10t-girls-yellow-rain.jpg",
                  },
                  {
                    id: 21,
                    category: "Men",
                    title: "Winter Jacket",
                    description: "Warm winter jacket to keep you cozy during the cold.",
                    price: 5999,
                    discount: 15,
                    rating: 4.7,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToA_g-Umi2H9TfWKEp95s4F64Ib73TExhrhFzMIRjORrr6e2i0_zWzvMsgTTPd8W-3nLc&usqp=CAU",
                  },
                  {
                    id: 22,
                    category: "Women",
                    title: "Maxi Dress",
                    description: "Flowy maxi dress for a casual summer look.",
                    price: 2499,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://media.6media.me/media/catalog/product/7/0/7006194928_2.jpg",
                  },
                  {
                    id: 23,
                    category: "Kids",
                    title: "Kids Tracksuit",
                    description: "Comfortable tracksuit for kids' sports activities.",
                    price: 1299,
                    discount: 20,
                    rating: 4.6,
                    thumbnail: "https://nwscdn.com/media/catalog/product/cache/h700xw700/f/o/forza-kids-full-tracksuit-navy-main_4.jpg",
                  },
                  {
                    id: 24,
                    category: "Men",
                    title: "Cargo Pants",
                    description: "Functional and stylish cargo pants for men.",
                    price: 1899,
                    discount: 12,
                    rating: 4.4,
                    thumbnail: "https://m.media-amazon.com/images/I/61F7X4QxieL._AC_UY350_.jpg",
                  },
                  {
                    id: 25,
                    category: "Women",
                    title: "Saree",
                    description: "Comfortable and fitting flexible clothes.",
                    price: 1999,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://assets.ajio.com/medias/sys_master/root/20230508/1J5g/64591d70d55b7d0c639d9d46/-473Wx593H-466138500-turquoise-MODEL.jpg",
                  },
                  {
                    id: 1,
                    title: "Modern Sofa Set",
                    description: "3-seater fabric sofa with wooden frame.",
                    price: 25999,
                    discount: 15,
                    rating: 4.7,
                    thumbnail: "https://cdn-idimj.nitrocdn.com/WhPAOrwwzgEUQpZxHSiIdKysEwgKQQkO/assets/images/optimized/rev-d5663d0/thehome.ae/wp-content/uploads/2023/11/999X665X100-OMAR-SOFA-1818B-11-1.jpg",
                  },
                  {
                    id: 2,
                    title: "Queen Size Bed",
                    description: "Wooden bed with hydraulic storage.",
                    price: 32999,
                    discount: 12,
                    rating: 4.6,
                    thumbnail: "https://ii1.pepperfry.com/media/catalog/product/t/a/1100x1210/takai-queen-size-bed-in-wenge-finish-by-mintwud-takai-queen-size-bed-in-wenge-finish-by-mintwud-wqhmtv.jpg",
                  },
                  {
                    id: 3,
                    title: "Dining Table Set",
                    description: "6-seater wooden dining table with chairs.",
                    price: 19999,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://damroimages.blob.core.windows.net/damroimages/Tency-1.jpg",
                  },
                  {
                    id: 4,
                    title: "Recliner Chair",
                    description: "Adjustable recliner with ergonomic design.",
                    price: 14999,
                    discount: 8,
                    rating: 4.7,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx0oOAByPT2dg2hzqjT1O8IN82pJcpFVkatA&s",
                  },
                  {
                    id: 5,
                    title: "Coffee Table",
                    description: "Solid wood coffee table with glass top.",
                    price: 5999,
                    discount: 20,
                    rating: 4.6,
                    thumbnail: "https://images.woodenstreet.de/image/data/coffee-table/elevate-sheesham-wood-glass-top-coffee-table-with-storage-walnut-finish/walnut-finish/new-logo/1.jpg",
                  },
                  {
                    id: 6,
                    title: "Bookshelf",
                    description: "5-tier wooden bookshelf for storage.",
                    price: 7999,
                    discount: 15,
                    rating: 4.5,
                    thumbnail: "https://m.media-amazon.com/images/I/61ewEvPy2wL._AC_UF894,1000_QL80_.jpg",
                  },
                  {
                    id: 7,
                    title: "TV Unit",
                    description: "Wall-mounted TV unit with storage shelves.",
                    price: 11999,
                    discount: 18,
                    rating: 4.4,
                    thumbnail: "https://m.media-amazon.com/images/I/71efO+QyxtL.jpg",
                  },
                  {
                    id: 8,
                    title: "Wardrobe",
                    description: "3-door wooden wardrobe with mirror.",
                    price: 22999,
                    discount: 12,
                    rating: 4.6,
                    thumbnail: "https://studiokook.com/cdn/shop/files/jw-min_4413659d-703f-45f5-8080-a5de21957569.jpg?v=1713250287",
                  },
                  {
                    id: 9,
                    title: "Study Table",
                    description: "Compact wooden study table with drawers.",
                    price: 7999,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://shop.gkwretail.com/cdn/shop/files/KidsStudyTable43.03_WoodenDesk1.webp?v=1690878967",
                  },
                  {
                    id: 10,
                    title: "Accent Chair",
                    description: "Upholstered accent chair with wooden legs.",
                    price: 5999,
                    discount: 15,
                    rating: 4.6,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1sHN6ioQDorW5Pz8Elo3fNS4znsEnfFanGg&s",
                  },
                  {
                    id: 11,
                    title: "Corner Shelf",
                    description: "Space-saving 4-tier corner shelf.",
                    price: 3499,
                    discount: 18,
                    rating: 4.4,
                    thumbnail: "https://vibecrafts.com/cdn/shop/files/vibecrafts-modern-corner-diamond-shape-wooden-wall-shelf-with-light-oak-finish-WWSVC_63010_1.jpg?v=1724994229",
                  },
                  {
                    id: 12,
                    title: "L-Shaped Sofa",
                    description: "Luxury L-shaped fabric sofa with cushions.",
                    price: 37999,
                    discount: 12,
                    rating: 4.8,
                    thumbnail: "https://www.orangetree.in/cdn/shop/files/Gallery-1ChiyoL-ShapedSofaBuyOnline.jpg?v=1722852692",
                  },
                  {
                    id: 13,
                    title: "Rocking Chair",
                    description: "Classic wooden rocking chair with cushion.",
                    price: 12999,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiMDBpiMQ7mdVGPP_9s6XXpgndjt-CV4sVCQ&s",
                  },
                  {
                    id: 14,
                    title: "Bedside Table",
                    description: "Compact wooden bedside table with drawer.",
                    price: 3999,
                    discount: 20,
                    rating: 4.5,
                    thumbnail: "https://ik.imagekit.io/2xkwa8s1i/img/bedside-tables/New/WBDSTCINDER/1.jpg?tr=w-3840",
                  },
                  {
                    id: 15,
                    title: "Office Chair",
                    description: "Ergonomic office chair with lumbar support.",
                    price: 9999,
                    discount: 12,
                    rating: 4.6,
                    thumbnail: "https://roswp-mediastorage.s3.ap-south-1.amazonaws.com/wp-content/uploads/2023/04/05111518/CE-High-Back-Ergonomic-Mesh-Office-Chairs-for-Work-from-Home.webp",
                  },
                  {
                    id: 16,
                    title: "Chaise Lounge",
                    description: "Elegant chaise lounge with velvet upholstery.",
                    price: 18999,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGN9aoSKMBJ_kyNBNu7_nnbUpPtEzgehHzaQ&s",
                  },
                  {
                    id: 17,
                    title: "Storage Ottoman",
                    description: "Multi-purpose ottoman with storage space.",
                    price: 4999,
                    discount: 15,
                    rating: 4.4,
                    thumbnail: "https://wallmantra.com/wp-content/uploads/WMCUSHTBLE-128-1.jpg",
                  },
                  {
                    id: 18,
                    title: "Bar Stool Set",
                    description: "Set of 2 adjustable bar stools.",
                    price: 8999,
                    discount: 18,
                    rating: 4.5,
                    thumbnail: "https://shop.gkwretail.com/cdn/shop/products/BarStoolModernPuLeatherKitchenCounterStoolsDiningChairsSetof2-3.jpg?v=1631353942",
                  },
                  {
                    id: 19,
                    title: "Entryway Bench",
                    description: "Wooden bench with shoe storage.",
                    price: 5999,
                    discount: 10,
                    rating: 4.6,
                    thumbnail: "https://images-cdn.ubuy.co.in/64b64c775070d50a911916d3-espresso-entryway-storage-bench-with.jpg",
                  },
                  {
                    id: 20,
                    title: "Kids Bunk Bed",
                    description: "Space-saving bunk bed with ladder.",
                    price: 24999,
                    discount: 12,
                    rating: 4.7,
                    thumbnail: "https://www.smartsters.in/cdn/shop/files/Artboard1_51ad51c8-48c3-42aa-ba09-286061d05e13.png?v=1711712106&width=1946",
                  },
                  {
                    id: 21,
                    title: "Vanity Table",
                    description: "Wooden vanity table with mirror and drawers.",
                    price: 15999,
                    discount: 15,
                    rating: 4.6,
                    thumbnail: "https://www.ikea.com/in/en/images/products/malm-dressing-table-white__1154625_pe886239_s5.jpg?f=s",
                  },
                  {
                    id: 22,
                    title: "Garden Chair Set",
                    description: "Set of 4 metal garden chairs.",
                    price: 12999,
                    discount: 20,
                    rating: 4.5,
                    thumbnail: "https://dreamlineoutdoorfurniture.com/cdn/shop/products/adele-95-cermaic-nivala-5pc-char.png?v=1680087229&width=1080",
                  },
                  {
                    id: 23,
                    title: "Sectional Sofa",
                    description: "Large sectional sofa with recliner.",
                    price: 45999,
                    discount: 12,
                    rating: 4.8,
                    thumbnail: "https://www.modholic.in/cdn/shop/products/MD-3356-GRY_01.jpg?v=1683681518",
                  },
                  {
                    id: 24,
                    title: "Futon Bed",
                    description: "Convertible futon bed with fabric upholstery.",
                    price: 15999,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://images-cdn.ubuy.qa/658eb38ac236be56b368e659-muumblus-55-5-pull-out-sofa-bed-2.jpg",
                  },
                  {
                    id: 25,
                    title: "Hall Tree",
                    description: "Coat rack and bench combo with storage.",
                    price: 8999,
                    discount: 15,
                    rating: 4.6,
                    thumbnail: "https://assets.wfcdn.com/im/10750211/resize-h800-w800%5Ecompr-r85/2778/277838362/Thirza+Hall+Tree+39.4%27%27+Wide+with+Shoe+Storage.jpg",
                  },
                  {
                    id: 1,
                    title: "Nike Air Max",
                    description: "Stylish and comfortable running shoes.",
                    price: 7999,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://static.nike.com/a/images/t_PDP_936_v1/f_auto,q_auto:eco/0ca73e26-13fb-4cf6-854d-aea2287675d3/AIR+MAX+90.png",
                  },
                  {
                    id: 2,
                    title: "Adidas Ultraboost",
                    description: "Boost your comfort with Adidas Ultraboost.",
                    price: 9999,
                    discount: 12,
                    rating: 4.7,
                    thumbnail: "https://assets.adidas.com/images/w_600,f_auto,q_auto/fc885d1de97246fc9183af9000da38a8_9366/Ultraboost_Light_Shoes_Black_HQ6340_01_standard.jpg",
                  },
                  {
                    id: 3,
                    title: "Puma RS-X",
                    description: "Bold and stylish sneakers for all-day wear.",
                    price: 8499,
                    discount: 8,
                    rating: 4.6,
                    thumbnail: "https://m.media-amazon.com/images/I/611hNY7ucBL._SL1500_.jpg",
                  },
                  {
                    id: 4,
                    title: "Reebok Nano X1",
                    description: "Cross-trainers designed for high-intensity workouts.",
                    price: 7499,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://cdn11.bigcommerce.com/s-21x65e8kfn/images/stencil/original/products/50143/207389/REE3888_1000_7__90199.1688493238.jpg",
                  },
                  {
                    id: 5,
                    title: "New Balance 990v5",
                    description: "Classic sneakers with premium comfort.",
                    price: 11999,
                    discount: 15,
                    rating: 4.8,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzaD_mE3LyxoGqVoEq3xtlaoh9uyKWRG6VdA&s",
                  },
                  {
                    id: 6,
                    title: "Adidas Ultraboost",
                    description: "Boost your comfort with Adidas Ultraboost.",
                    price: 9999,
                    discount: 12,
                    rating: 4.7,
                    thumbnail: "https://assets.adidas.com/images/w_600,f_auto,q_auto/33a99fbbd8df40008ffeaf3c00819dfc_9366/Valentines_Day_Ultraboost_1.0_Shoes_White_HQ3857_HM1.jpg",
                  },
                  {
                    id: 7,
                    title: "Nike Air Zoom Pegasus 38",
                    description: "Premium running shoes for everyday runners.",
                    price: 7499,
                    discount: 10,
                    rating: 4.6,
                    thumbnail: "https://5.imimg.com/data5/ECOM/Default/2023/3/292916168/TX/UB/IH/105112946/195242665022-3-500x500.jpg",
                  },
                  {
                    id: 8,
                    title: "Reebok Classic Leather",
                    description: "Casual leather sneakers with classic design.",
                    price: 6499,
                    discount: 15,
                    rating: 4.4,
                    thumbnail: "https://def-live.cdn.aboutyou.cloud/images/591fb865820e9250a1c5df06ddb03a0c.jpg?quality=75&height=832&width=596",
                  },
                  {
                    id: 9,
                    title: "Asics Gel-Kayano 28",
                    description: "Stability shoes for long-distance running.",
                    price: 12999,
                    discount: 18,
                    rating: 4.8,
                    thumbnail: "https://cdn.shopify.com/s/files/1/0258/5411/5893/products/1012B272_101_SB_FR_GLB.webp?v=1662582865",
                  },
                  {
                    id: 10,
                    title: "Under Armour HOVR Phantom 2",
                    description: "High-performance shoes for runners with HOVR technology.",
                    price: 10999,
                    discount: 20,
                    rating: 4.7,
                    thumbnail: "https://www.underarmour.in/media/wysiwyg/FW22_RUN_HOVR_Phantom3_Site_2_1_M_4_2.jpg",
                  },
                  {
                    id: 11,
                    title: "Converse Kids Sneakers",
                    description: "Colorful sneakers for kids.",
                    price: 2999,
                    discount: 5,
                    rating: 4.3,
                    thumbnail: "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dw82d6e34e/images/d_08/3J231_D_08X1.jpg?sw=406",
                  },
                  {
                    id: 12,
                    title: "Nike Kids Air Force 1",
                    description: "Iconic sneakers for kids with a clean, stylish look.",
                    price: 4999,
                    discount: 8,
                    rating: 4.6,
                    thumbnail: "https://static.nike.com/a/images/t_default/e125b578-4173-401a-ab13-f066979c8848/AIR+FORCE+1+%28GS%29.png",
                  },
                  {
                    id: 13,
                    title: "Adidas Kids Superstar",
                    description: "Classic shell-toe sneakers for kids.",
                    price: 3999,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/795f45401b6548c0bdb1ab2300c254c1_9366/Superstar_Shoes_White_EF4842_01_standard.jpg",
                  },
                  {
                    id: 14,
                    title: "Puma Kids Future Rider",
                    description: "Stylish sneakers designed for energetic kids.",
                    price: 4499,
                    discount: 12,
                    rating: 4.4,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPH7ZNG5FnQ-YGyml2DHJs1X4xAHBPILin3w&s",
                  },
                  {
                    id: 15,
                    title: "New Balance Kids 574",
                    description: "Comfortable sneakers for active kids.",
                    price: 3699,
                    discount: 5,
                    rating: 4.3,
                    thumbnail: "https://sportland.com/media/catalog/product/cache/a93584b4c19196955ba77379dc459454/P/V/PV574EVG_GRE_96a5.jpg",
                  },
                  {
                    id: 16,
                    title: "Nike Basketball Shoes",
                    description: "High-performance basketball shoes.",
                    price: 8999,
                    discount: 15,
                    rating: 4.8,
                    thumbnail: "https://static.nike.com/a/images/t_default/5eb3d983-e731-4a7a-8990-446d231c2229/NIKE+AIR+MAX+IMPACT+4.png",
                  },
                  {
                    id: 17,
                    title: "Adidas Predator Football Boots",
                    description: "Football boots with an iconic design.",
                    price: 9999,
                    discount: 10,
                    rating: 4.7,
                    thumbnail: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7bcf674f57fd4d78b87d0ec3f9c9251d_9366/Predator_Club_Sock_Flexible_Ground_Football_Boots_Black_IG7742_22_model.jpg",
                  },
                  {
                    id: 18,
                    title: "Under Armour HOVR Sonic 3",
                    description: "Running shoes designed for speed and comfort.",
                    price: 10999,
                    discount: 18,
                    rating: 4.6,
                    thumbnail: "https://cdn11.bigcommerce.com/s-zut1msomd6/images/stencil/500x659/products/41322/244065/under-armour-womens-hovr-sonic-6-3026128-103white-white_olive-tint_grove-green-pair__67491.1.jpg",
                  },
                  {
                    id: 19,
                    title: "Puma Ignite Speed 2",
                    description: "Performance running shoes for fast athletes.",
                    price: 8499,
                    discount: 12,
                    rating: 4.5,
                    thumbnail: "https://images-static.nykaa.com/media/catalog/product/tr:h-800,w-800,cm-pad_resize/e/d/ed77ad9pm_19091202_1_.jpg",
                  },
                  {
                    id: 20,
                    title: "Reebok Crossfit Nano 9",
                    description: "Crossfit shoes built for maximum performance.",
                    price: 7999,
                    discount: 15,
                    rating: 4.7,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAvy6XgBWpbKrLvW6MM5pvLpLavpSAZETU1g&s",
                  },
                  {
                    id: 21,
                    title: "Boots Collection",
                    description: "Stylish boots for all seasons.",
                    price: 6499,
                    discount: 20,
                    rating: 4.6,
                    thumbnail: "https://rukminim1.flixcart.com/image/300/300/k2arbm80/shoe/f/m/v/kjuis-1099-36-kajmi-white-original-imafh9bapprrw3z6.jpeg",
                  },
                  {
                    id: 22,
                    title: "Timberland PRO Work Boots",
                    description: "Durable work boots for tough conditions.",
                    price: 13999,
                    discount: 15,
                    rating: 4.8,
                    thumbnail: "https://cdn.shopify.com/s/files/1/1107/6454/files/TB092615214_alt4_7004f256-e5db-4d33-bf4f-5aa25c2e4a74.jpg",
                  },
                  {
                    id: 23,
                    title: "Dr. Martens 1460 Boots",
                    description: "Iconic leather boots with a rebellious edge.",
                    price: 12999,
                    discount: 10,
                    rating: 4.5,
                    thumbnail: "https://cdn.media.amplience.net/i/drmartens/14353001.84?$smart576$&fmt=auto",
                  },
                  {
                    id: 24,
                    title: "UGG Classic Tall Boots",
                    description: "Cozy and warm boots for winter.",
                    price: 10999,
                    discount: 12,
                    rating: 4.6,
                    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOV1c2kG5aJ8Cw0rzopeSQAYoHbDespi80uA&s",
                  },
                  {
                    id: 25,
                    title: "Sorel Joan of Arctic Boots",
                    description: "Waterproof winter boots with insulation.",
                    price: 11999,
                    discount: 18,
                    rating: 4.7,
                    thumbnail: "https://applesaddlery.vtexassets.com/arquivos/ids/509605/Sorel-1855131-010-Front.jpg?v=638241146402900000",
                  },

  ];

  export default products;
